name: cicd

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  cicd:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
      
      - name: Lint Code Base
        uses: super-linter/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.WRKFLW_TOKEN }}

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: build Java Code
        run: mvn clean package
  
      - name: Run Unit test
        run: mvn test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: build docker image
        run: docker build -t mayuratverticurl/javaapp .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push to DockerHub
        run: docker push mayuratverticurl/javaapp:latest
